name: Build
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '12'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: npm test
            - name: semantic-release
              if: success() && github.ref == 'refs/heads/master'
              run: npm run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
